### ISSUE TITLE
Register 54 Documentation incorrect

### ISSUE THREAD

**Issue by Jurian15** [jrmno/Ecoforest_Heatpump_Modbus#1]
Hi @jrmno,

Thanks a lot for this extensive list of registers.
If my testing is correct, register 54 is the register for the fixed temperature for DG1, could you change that?

Kind regards,
Jurian

**Comment by jrmno** [comment]
Hey @Jurian15 

I changed the description for Analog 54 & 73 so it makes more sense.

thx.
